version: '3'

env:
  ENV: testnet

dotenv: ['.env.{{.ENV}}', '.env']

tasks:

  default:
    cmds:
      - task --list-all

  test:
    cmds:
      - pnpm run test

  lint:
    cmds:
      - pnpm run lint

  build:
    cmds:
      - pnpm run build

  build-and-deploy:
    cmds:
      - pnpm run build
      - cd build && zip -r {{.ZIP_FILE_NAME}} .
      - cd build && aws s3 sync . s3://{{.LAMBDA_S3}}/{{.LAMBDA_VERSION}} --exclude "*" --include "{{.ZIP_FILE_NAME}}"
      - aws lambda update-function-code --function-name {{.LAMBDA_ARN}} --region eu-west-1 --s3-bucket {{.LAMBDA_S3}} --s3-key {{.LAMBDA_VERSION}}/{{.ZIP_FILE_NAME}}
