name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  TEST_MNEUMONIC_TESTNET: ${{ secrets.TEST_MNEUMONIC_TESTNET }}
  TEST_ADDRESS_TESTNET: ${{ secrets.TEST_ADDRESS_TESTNET }}
  TEST_BOT_URL: ${{ secrets.TEST_BOT_URL }}
  TEST_DISCORD_TOKEN: ${{ secrets.TEST_DISCORD_TOKEN }}
  DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}

jobs:
  serverless:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm 
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Run tests
        run: task test
